tempo:
  server:
    http_listen_port: 3200
    grpc_server_max_recv_msg_size: 104857600 # 100MB in bytes

  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_http:
          endpoint: 0.0.0.0:14268
    opencensus:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
          max_recv_msg_size_mib: 100 # 100MB
        http:
          endpoint: "0.0.0.0:4318"

  metricsGenerator:
    enabled: true
    storage:
      path: "/var/tempo/generator/wal"
      remote_write_flush_deadline: 1m
    processor:
      service_graphs:
        max_items: 10000
        wait: 10s
        workers: 10
        dimensions:
          - client
          - server
          - connection_type

  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
          - local-blocks
        storage:
          path: "/var/tempo/generator/wal"
        remoteWriteUrl: http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/write  

serviceMonitor:
  enabled: true
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
  interval: 15s
  scrapeTimeout: 10s
