# Values for grafana/k8s-monitoring-helm
# Add custom values as needed

clusterMetrics: 
  enabled: true
  node-exporter:
    service:
      port: 9123 
cluster:
  name: my-cluster-name
destinations:
- name: Prometheus
  type: prometheus
  url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
- name: Loki
  type: loki
  url: http://loki.monitoring.svc.cluster.local:3100
- name: Tempo
  type: otlp
  url: http://tempo.monitoring.svc.cluster.local:3100
alloy-metrics:
  enabled: true
  