cluster:
  name: my-cluster-name
prometheus:
  enabled: true
grafana:
  enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3100
alertmanager:
  enabled: true
kube-state-metrics:
  enabled: false
nodeExporter:
  enabled: false
