alertmanager:
  replicas: 1
  resources: {}
  statefulSet:
    enabled: true

compactor:
  resources: {}

distributor:
  replicas: 1
  resources: {}

ingester:
  replicas: 1
  resources: {}

  zoneAwareReplication:
    enabled: false

admin-cache:
  enabled: false

chunks-cache:
  enabled: false

index-cache:
  enabled: false

metadata-cache:
  enabled: false

results-cache:
  enabled: false

overrides_exporter:
  replicas: 1
  resources: {}

querier:
  replicas: 1
  resources: {}

query_frontend:
  replicas: 1
  resources: {}

ruler:
  replicas: 1
  resources: {}

store_gateway:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    size: 10Gi
  replicas: 1
  resources: {}

nginx:
  image:
    registry: crpxpssiproxyweuprd001.azurecr.io/docker.io
  replicas: 1
  resources: {}

gateway:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - gateway
            topologyKey: kubernetes.io/hostname

mimir:
  structuredConfig:
    multitenancy_enabled: false

serviceAccount:
  create: false
  name: minio-sa
