admin:
  userKey: admin-user
  passwordKey: admin-password
adminUser: admin
adminPassword: supersecretpassword

envValueFrom:
  GF_DATABASE_PASSWORD:
    secretKeyRef:
      name: grafana-postgresql-auth
      key: password

datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: Mimir
        uid: mimir
        type: prometheus
        access: proxy
        url: http://mimir-query-frontend.monitoring.svc.cluster.local:8080/prometheus
        isDefault: true
        editable: false
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        editable: false
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: fake
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        editable: false
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          lokiSearch:
            datasourceUid: loki
          serviceMap:
            datasourceUid: mimir
          tracesToLogsV2:
            datasourceUid: loki
          tracesToMetrics:
            datasourceUid: mimir
        secureJsonData:
          httpHeaderValue1: fake
      - name: Alertmanager
        uid: alertmanager
        type: alertmanager
        access: proxy
        url: http://mimir-alertmanager.monitoring.svc.cluster.local:8080/alertmanager
        editable: false
        jsonData:
          implementation: mimir
grafana.ini:
  auth:
    managed_service_accounts_enabled: true
  database:
    type: postgres
    host: postgresql.monitoring.svc.cluster.local:5432
    name: grafana
    user: grafana
    password: ${GF_DATABASE_PASSWORD}
    ssl_mode: disable
  feature_toggles:
    enable: externalServiceAccounts

persistence:
  enabled: true
  type: pvc
  accessModes:
    - ReadWriteOnce
  size: 1Gi
