apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/your-gitops-repo.git' # Update to your repo URL
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # App of Apps pattern: list all sub-apps
  sources:
    - path: apps/kube-prometheus-stack.yaml
    - path: apps/k8s-monitoring-helm.yaml
    - path: apps/loki.yaml
    - path: apps/tempo.yaml
