apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: "*"
    helm:
      values: |
        features:
          clusterMetrics: 
            enabled: true
        cluster:
          name: my-cluster-name
        grafana:
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki.monitoring.svc.cluster.local:3100
            - name: Tempo
              type: tempo
              access: proxy
              url: http://tempo.monitoring.svc.cluster.local:3100
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
