apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: "*"
    helm:
      values: |
        clusterMetrics: 
          enabled: true
          node-exporter:
            service:
              port: 9123 
        cluster:
          name: my-cluster-name
        destinations:
        - name: Prometheus
          type: prometheus
          url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        - name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
        - name: Tempo
          type: otlp
          url: http://tempo.monitoring.svc.cluster.local:3100
        alloy-metrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
