apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: "*"
    helm:
      valueFiles:
      - /helm/k8s-monitoring-helm-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
