apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring-helm
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://git.example.com/org/value-files.git'
      targetRevision: dev
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: k8s-monitoring
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/charts/k8s-monitoring/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
