apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/GVengelen/grafana.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/charts/tempo/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
